openapi: 3.0.0
info:
  title: Mother Earth Womens Wellness API Swagger
  description: Mother Earth Womens Wellness API documentation
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Mero Vision
    url: https://merovision.com
    email: merovision720@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: https://api.motherearthwomenswellness.com/
    description: server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
tags:
  - name: Admin
  - name: Admin > Auth
  - name: Admin > Site Settings
  - name: Admin > Contact Us
  - name: Admin > Faq
  - name: Admin > Gallery
  - name: Website
  - name: Website > Auth
  - name: Website > Contact Us
  - name: Website > Faq
  - name: Website > Gallery
  - name: Website > Client
paths:
  /api/admin/login:
    post:
      tags:
        - Admin > Auth
      summary: admin login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: info@motherearthwomenswellness.com
                password:
                  type: string
                  example: Password
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/site-settings:
    post:
      tags:
        - Admin > Site Settings
      summary: store site settings
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                website_title:
                  type: string
                  example: Mother Earth Woman Wellness
                website_slogan:
                  type: string
                  example: Mother Earth Woman Well
                logo:
                  type: string
                  format: binary
                fav_icon:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Site Settings
      summary: show all site settings data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/contact-us:
    get:
      tags:
        - Admin > Contact Us
      summary: show all contact us
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: pagination_limit
          in: query
          schema:
            type: integer
          example: '8'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/contact-us/{id}:
    delete:
      tags:
        - Admin > Contact Us
      summary: delete contact us
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/faq:
    post:
      tags:
        - Admin > Faq
      summary: store faq
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                question:
                  type: string
                  example: hy
                answer:
                  type: string
                  example: hy
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Faq
      summary: show all faq
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/faq/{id}:
    post:
      tags:
        - Admin > Faq
      summary: update faq
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                quation:
                  type: string
                answer:
                  type: string
                _method:
                  type: string
                  example: PUT
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Admin > Faq
      summary: delete faq
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/gallery:
    post:
      tags:
        - Admin > Gallery
      summary: store gallery images
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                gallery_title:
                  type: string
                  example: hy
                images[]:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Admin > Gallery
      summary: show all gallery images
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/admin/gallery/{id}:
    get:
      tags:
        - Admin > Gallery
      summary: show single gallery album
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Admin > Gallery
      summary: delete gallery images
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/login:
    post:
      tags:
        - Website > Auth
      summary: client login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: hanciephago@gmail.com
                password:
                  type: string
                  example: Password@720
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/mobile-signup:
    post:
      tags:
        - Website > Auth
      summary: mobile signup
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Hancie Phago
                mobile_no:
                  type: integer
                  example: '9825456556'
                email:
                  type: string
                  example: hanciephago@gmail.com
                password:
                  type: string
                  example: Password@720
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/verify-account:
    post:
      tags:
        - Website > Auth
      summary: verify mobile otp
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                token:
                  type: integer
                  example: '67380'
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/contact-us:
    post:
      tags:
        - Website > Contact Us
      summary: store contact us data
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: hy
                email:
                  type: string
                  example: hy@gmail.com
                mobile_no:
                  type: integer
                  example: '34354365'
                subject:
                  type: string
                  example: hy
                message:
                  type: string
                  example: hy
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/faq:
    get:
      tags:
        - Website > Faq
      summary: show all faqs
      security:
        - noauthAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/gallery:
    get:
      tags:
        - Website > Gallery
      summary: show all gallery images
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/gallery/{slug}:
    get:
      tags:
        - Website > Gallery
      summary: show single gallery image
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: slug
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/client/user/{id}:
    get:
      tags:
        - Website > Client
      summary: show authenticated client data
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/client/change-password:
    post:
      tags:
        - Website > Client
      summary: change password
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
